# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70de5095537e7065e76834f1062219f4f130093820353bae8be9a22116fa9ae8d37c85aa1fd3bb8175880a732f8c13c0c54d97d1c080dbbf1340e4f475111ad5

test:
  secret_key_base: 8eaf4594b152ceb7a2f1834c982997308d4aa4a7929686f5bd46de2ce26d5115f0fc9ea180f0151d5476a099fb4457561e1b5db73b2deb63466549c0f7a5a328

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
